version: '3'
services:
  postgres:
    image: postgres
    container_name: postgres96
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - /docker-entrypoint-initdb.d
    ports:
      - 5434:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    